//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLVIII_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizzaOrder
    {
        public int ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PizzaID { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblPizza tblPizza { get; set; }
    }
}
